In [1]:
import numpy as np
points=np.array([[ 970.44746163,  396],
 [ 998.78276269  ,397],
 [1071.98229044  ,400],
 [1220.74262102  ,396],
 [ 999.96340024  ,417]])

In [43]:
points=np.random.randint(1000, size=(5, 2))

In [44]:
centroids=np.mean(points,axis=0)

In [45]:
centroids

array([648.2, 662. ])

In [46]:
pts = points - centroids

In [47]:
pts

array([[ 342.8, -176. ],
       [ 230.8,  276. ],
       [-240.2,  280. ],
       [-101.2, -132. ],
       [-232.2, -248. ]])

In [48]:
np.square(pts)

array([[117511.84,  30976.  ],
       [ 53268.64,  76176.  ],
       [ 57696.04,  78400.  ],
       [ 10241.44,  17424.  ],
       [ 53916.84,  61504.  ]])

In [49]:
np.sqrt(np.sum(np.square(pts),axis=1))

array([385.34119946, 359.78415752, 368.91196782, 166.32931191,
       339.73642725])

In [50]:
V = np.sum(np.sqrt(np.sum(np.square(pts),axis=1)))

In [51]:
V

1620.10306395169

In [52]:
k = 5*np.sqrt(2)/V

In [53]:
k

0.0043645790006828404

In [54]:
k*points

array([[4.32529779, 2.12118539],
       [3.83646494, 4.0939751 ],
       [1.78074823, 4.11143342],
       [2.38742471, 2.31322687],
       [1.81566486, 1.80693571]])

In [58]:
np.sum(np.sqrt(np.sum(np.square(k*(points - centroids)),axis=1)))/5

1.4142135623730954

In [56]:
np.sqrt(2)

1.4142135623730951

In [57]:
V*k/5

1.4142135623730951